Repository kubevirt/kubectl-virt-plugin, pull requests merged in 2020-12, with the labels that each got.

#26 Make validation of krew manifest work, rely on GIT_ASKPASS
  images/builder/Dockerfile
  scripts/functions
Labels: dco-signoff: yes, size/M

#27 Remove injection of token into URL
  scripts/functions
Labels: dco-signoff: yes, size/XS

#28 Build image on top of kubevirtci/bootstrap
  images/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#29 Add build_all for prow job
  images/Makefile
Labels: dco-signoff: yes, size/XS

#30 Use krew release bot instead of creating PR
  .github/workflows/krew-release-bot.yaml
  .krew.yaml
  images/builder/Dockerfile
  scripts/create-krew-index-pr.sh
  scripts/create-krew-yaml.sh
  scripts/create-pull-request.sh
  scripts/create-release.sh
  scripts/functions
  scripts/test-krew-package-linux.sh
Labels: dco-signoff: yes, size/L
